version: "3.9"

services:
  bdio-app:
    build:
      context: .
    volumes:
      - ./bdio_backend:/bdio_backend
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py move_media && gunicorn bdio_backend.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - bdio-db
      - redis
      - daphne
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - bdio-app
    env_file:
      - ./.env
    volumes:
      - dev-static-data:/vol/web
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - /certbot/conf:/etc/letsencrypt
      - /certbot/www:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot --force-renewal --email nauczajka.info@gmail.com -d ${CERTBOT_DOMAIN} --agree-tos
    env_file:
      - ./.env

  daphne:
    build:
      context: .
    command: >
      daphne --bind 0.0.0.0 -p 8003 bdio_backend.asgi:application
    ports:
      - "8003:8003"
    env_file:
      - ./.env

  bdio-db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  dev-static-data:
